export const SECTORSCONSTANTS = [
  "agriculture",
  "automobile",
  "banking, financial services & insurance",
  "beauty and wellness",
  "chemicals & petrochemicals",
  "construction & real estate",
  "education & skill development",
  "electronics & it hardware",
  "fmcg",
  "food processing",
  "furniture & furnishing",
  "gems & jewellery",
  "handicraft",
  "healthcare & pharmaceuticals",
  "home services",
  "it & ites",
  "leather & leather goods",
  "logistics & warehousing",
  "manufacturing & heavy engineering",
  "media & entertainment",
  "mining",
  "oil & gas",
  "power",
  "private security",
  "professional & other services",
  "retail",
  "telecommunication",
  "textile & apparel",
  "tourism, hospitality & travel",
  "E commerce",
  "telecom",
  "FMCG",
  "FMCD",
  "others",
];
