 const SKILLS_CONSTANTS = [
  "agricultural machinery operator",
  "Area sales manager",
  "bamboo/ timber grower",
  "beekeeper",
  "dairy farmer",
  "farm/ plantation worker",
  "farmer",
  "fisherman",
  "floriculturist",
  "gardener",
  "goat/ pig farmer",
  "irrigation service technician",
  "poultry farmer",
  "pump mechanic",
  "sericulturist",
  "soil sampler/ collector",
  "tractor mechanic",
  "Territory sales incharge",
  "Furniture Packer",
  "automotive sales consultant",
  "automotive service technician (2 & 3 wheeler)",
  "automotive service technician (4 wheeler)",
  "driver (autorikshaw/car/ taxi)",
  "driver (bus/commercial vehicle)",
  "mechanic (auto)",
  "mechanic (diesel engine)",
  "mechanic auto body painting",
  "mechanic auto body repair",
  "mechanic auto electrical & electronics",
  "business correspondent & facilitator",
  "debt recovery agent",
  "equity dealer",
  "front desk officer - financial institutions",
  "gst- accounts assistant",
  "insolvency & bankruptcy associate",
  "insurance agent",
  "life insurance agent",
  "loan approval officer",
  "loan processing officer",
  "microfinance executive",
  "mutual fund agent",
  "barber",
  "beauty & wellness consultant",
  "beauty therapist",
  "fitness trainer",
  "hair stylist",
  "mehendi specialist",
  "pedicurist & manicurist",
  "Spa therapist",
  "tattoo artist",
  "yoga instructor",
  "Catalog specialist",
  "Cluster manager ",
  "Customer service associate",
  "Image Editor",
  "Design Consultant",
  "chemical engineer (design)",
  "chemical engineer (plant)",
  "chemical plant operator",
  "chemical process technician",
  "lab assistant (chemical plant)",
  "maintenance mechanic (chemical plant)",
  "architect",
  "autocad engineer",
  "barbender & steel fixer",
  "civil engineer",
  "construction site engineer",
  "construction supervisor",
  "construction worker",
  "draughtsman (civil)",
  "electrician",
  "façade installer",
  "land surveyor",
  "land/ real estate buyer",
  "marble granite polish operator",
  "mason",
  "painter & decorator",
  "plumber",
  "real estate consultant",
  "scaffolder",
  "Sales Specialist",
  "Sales Manager",
  "shuttering carpenter",
  "educational content creator",
  "martial arts trainer (judo/karate/taekwando)",
  "teacher (higher education)",
  "teacher (music & arts)",
  "teacher (physical & sports)",
  "teacher (pre-primary & primary)",
  "teacher (secondary & higher secondary)",
  "teacher (special needs)",
  "teacher (vocational & technical)",
  "circuit design engineer",
  "electronics assembly operator",
  "electronics testing technician",
  "embedded software engineer",
  "field engineer - tv",
  "field technician - ac",
  "field technician - computing & peripherals",
  "field technician - other home appliances",
  "field technician - refrigerator",
  "field technician - ups & inverter",
  "field technician - washing machine",
  "hardware tester",
  "mobile phone hardware repair technician",
  "set top box installation & repair technician",
  "solar panel installation technician",
  "solar pv system installation engineer",
  "solar pv system repair technician",
  "vlsi design engineer",
  "brand manager",
  "marketing executive",
  "marketing manager",
  "packaging technician",
  "production manager",
  "sales executive",
  "sales manager",
  "agriculture produce buyer",
  "baker",
  "cold storage technician",
  "dairy products processor",
  "fish & seafood processor",
  "food products packaging technician",
  "fruits & vegetables processor",
  "grain miller",
  "meat & poultry processor",
  "pulse processing technican",
  "carpenter - wooden furniture",
  "delivery & installation executive - furniture & fitting",
  "fitter - modular furniture",
  "installer - glassdoors & windows",
  "interior designer",
  "sales executive - furniture & fittings",
  "diamond processor",
  "diamond set jewellery maker",
  "gemstone processor",
  "goldsmith",
  "imitation jewellery maker",
  "jewellery retailer",
  "agarbatti maker (handicraft)",
  "bambooware maker (handicraft)",
  "carpet maker (handicraft)",
  "ceramic ware maker (handicraft)",
  "fashion jewellery maker (handicraft)",
  "glassware maker (handicraft)",
  "metalware maker (handicraft)",
  "paper mache artisan (handicraft)",
  "stonecraft maker (handicraft)",
  "woodware maker (handicraft)",
  "arogya mitra",
  "assistant physiotherapist",
  "dentist",
  "dietician",
  "doctor (aayush)",
  "doctor (allopathic)",
  "front line health worker",
  "geriatric care assistant",
  "home health aide",
  "hospital/ clinic administrator",
  "medical lab technician",
  "medical sales representative",
  "medical technician (any specialty)",
  "nurse",
  "patient relations associate (hospital)",
  "pharmacist",
  "pharmacy assistant",
  "physiotherapist",
  "psychological counseller",
  "speech audio therapy assistant",
  "telehealth services coordinator",
  "caregiver - newborn & mother",
  "caregiver - special needs",
  "child caretaker",
  "deep cleaning assistant",
  "domestic cook",
  "domestic maid",
  "elderly caretaker",
  "laundry executive",
  "associate data analyst",
  "cloud application developer",
  "cloud infrastructure analyst",
  "computer operator",
  "customer service executive (non-voice)",
  "customer service executive (voice)",
  "data entry operator",
  "data scientist",
  "database administrator",
  "devops engineer",
  "iot engineer",
  "it consultant",
  "it security analyst",
  "site reliability engineer",
  "software architect",
  "software developer",
  "software engineer",
  "software product manager",
  "software qa engineer",
  "technical writer",
  "test engineer",
  "ui developer",
  "user experience designer",
  "web & mobile application developer",
  "web developer",
  "footwear & allied goods repairer",
  "footwear & leather goods seller",
  "leather goods & garments maker",
  "leather worker",
  "saddle maker",
  "shoe & footwear maker",
  "cargo equipment handler",
  "cargo handler",
  "courier associate",
  "driver (truck/ tanker)",
  "exim executive",
  "vessel operator",
  "warehouse associate",
  "cnc/ vmc machine operator",
  "draughtsman (mechanical)",
  "electrical engineer",
  "electroplater",
  "fire technology & industrial safety engineer",
  "fitter",
  "foundry man technician",
  "ibr welder",
  "industrial painter",
  "instrument mechanic",
  "lift and escalator mechanic",
  "machinist",
  "machinist (grinder)",
  "marine fitter",
  "mechanic (mining machinery)",
  "mechanic (refrigeration & ac)",
  "mechanic lens/prism grinding",
  "mechanic machine tools maintenance",
  "mechanic mechatronics",
  "mechanic medical electronics",
  "mechanical engineer",
  "operator advanced machine tools",
  "plant supervisor",
  "plastic processing operator",
  "plumber (industrial)",
  "pump operator-cum-mechanic",
  "refractory technician",
  "rubber technician",
  "sheet metal worker",
  "spinning technician",
  "technician power electronic system",
  "tool & die maker (dies & moulds)",
  "tool & die maker (press tools",
  "jigs & fixtures)",
  "turner",
  "welder",
  "helper (industrial)",
  "actor",
  "animator",
  "cameraman",
  "character designer",
  "clean-up artist",
  "colourist",
  "compositor",
  "dancer",
  "graphic designer",
  "hairdresser",
  "journalist",
  "layout designer",
  "Loader",
  "Regional sales manager",
  "Program manager",
  "Process Associate",
  "Key account Manager",
  "Horeca development executive",
  "Business development manager",
  "Store manager",
  "Creative head",
  "lighting artist",
  "make-up artist",
  "music programmer",
  "production assistant",
  "props master",
  "prosthetics artist",
  "rendering artist",
  "search engine optimization executive",
  "set decorator",
  "singer",
  "social media executive",
  "sound designer",
  "sound editor",
  "sound engineer",
  "storyboard artist",
  "texturing artist",
  "vfx editor",
  "voice over artist",
  "blaster",
  "drill operator",
  "fireman",
  "geological assistant/ sampler",
  "gis modelling technician",
  "heavy earth moving machinery (hemm) operator",
  "helper/ assistant (mining operations)",
  "hemm mechanic",
  "mine driller (exploration)",
  "mine electrician",
  "mining machinist",
  "mining survey assistant",
  "ore processing operator",
  "underground mining machinery operator (any)",
  "drilling technician",
  "production technician",
  "petrol pump attendant",
  "petrol pump supervisor",
  "lpg mechanic",
  "petroleum engineer",
  "electricity meter technician",
  "lineman",
  "cctv supervisor",
  "personal security officer",
  "private investigator",
  "security guard (armed)",
  "security guard (unarmed)",
  "security supervisor",
  "astrologer",
  "event manager",
  "gst consultant",
  "income tax consultant",
  "lawyer",
  "legal assistant",
  "management consultant",
  "priest",
  "typist",
  "scientist",
  "social worker",
  "distributor salesman",
  "fish & meat vendor",
  "fresh fruits & vegetable vendor",
  "merchandiser",
  "retail cashier",
  "retail operations assistant",
  "retail sales associate",
  "store manager",
  "visual merchandiser",
  "broadband technician",
  "fttx installer",
  "in-store promoter",
  "line assembler - telecom products",
  "network administrator",
  "optical fiber splicer",
  "optical fiber technician",
  "r f site surveyor",
  "sales executive broadband",
  "telecom embedded hardware developer",
  "telecom network security technician",
  "telecom surface mount technology (smt) technician",
  "telecom technician - iot device/system",
  "telecom terminal equipment application developer",
  "telecom tower / bay installation supervisor",
  "tower technician",
  "wireless technician",
  "hand embroiderer",
  "knitter",
  "sewing machine operator",
  "tailor",
  "weaver (handloom)",
  "weaver (powerloom)",
  "fashion designer",
  "textile mechatronics technician",
  "textile wet processing technician",
  "weaving technician",
  "bartender",
  "bellboy",
  "chef",
  "commis chef (chef assistant)",
  "concierge",
  "cook/ kitchen steward",
  "food & beverages steward",
  "guest relations executive",
  "hotel front office associate",
  "housekeeping executive",
  "restaurant manager",
  "tourist guide",
  "travel consultant",
  "accountant",
  "administration executive",
  "behavioral/ motivational trainer",
  "business analyst",
  "business development manger",
  "data analyst",
  "digital marketer",
  "hr executive",
  "hr manager",
  "legal compliance executive",
  "mis executive",
  "purchase executive/ manager",
  "quality controller",
  "receptionist",
  "recruiter",
  "safety officer",
  "strategy/ planning manager",
  "supply chain manager",
  "others",
];

export default SKILLS_CONSTANTS;