export const SKILLS = [
  "Html",
  "Angular JS",
  "JavaScript",
  "CSS",
  "Web Designing",
  "Wordpress",
  "JQuery",
  "Bootstrap",
  "Flutter",
  "ReactNative",
  "Lead Generation",
  "Good Communication skills",
  "B2B Sales / Corporate Sales",
  "B2C Sales",
  "Product Demonstration",
  "Clint Relationship Management",
  "Other",
];
