const university =
["Academy of Maritime Education and Training",
"Acharya N.G.Ranga Agricultural University",
"Acharya Nagarjuna University",
"Adikavi Nannaya University",
"Ahmedabad University",
"AISECT Unviersity",
"Alagappa University",
"Aliah University",
"Aligarh Muslim University",
"All India Council of Technical Education",
"All India Institute of Medical Sciences(AIIMS)",
"AMITY University Haryana",
"Amity University Uttar Pradesh",
"Amity University, Rajasthan",
"Amrita Vishwa Vidyapeetham",
"Anand Agricultural Univerisity",
"Andhra University",
"Anna University",
"Anna University of Technology Coimbatore",
"Anna University of Technology Madurai",
"Anna University of Technology Tiruchirapalli",
"Anna University of Technology Tirunelveli",
"Annamalai University",
"Apeejay Stya University",
"Arni University",
"Assam Agricultural University",
"Assam Don Bosco University",
"Assam University",
"Avinashilingam Institute for Home Science & Higher Education for Women",
"Awadesh Pratap Singh University",
"Ayush and Health Sciences University of Chhattisgarh",
"B.L.D.E. University",
"B.S. Abdul Rahman Institute of Science & Technology",
"Baba Farid University of Health Sciences",
"Baba Ghulam Shah Badshah University",
"Babasaheb Bhimrao Ambedkar Bihar University",
"Babasaheb Bhimrao Ambedkar University",
"Baddi University of Emerging Science & Technology",
"Banaras Hindu University",
"Banasthali Vidyapith",
"Bangalore University",
"Barkatullah University",
"Bastar University",
"Berhampur University",
"Bhagat Phool Singh Mahila Vishwavidyalaya",
"Bhagwant University",
"Bharat Ratna Dr. B.R. Ambedkar University",
"Bharath University",
"Bharathiar University",
"Bharathidasan University",
"Bharati Vidyapeeth",
"Bhatkhande Music Institute",
"Bhupendra Narayan Mandal University",
"Bidhan Chandra Krishi Vishwavidyalaya",
"Bihar Yoga Bharati",
"Biju Patnaik University of Technology",
"Birla Institute of Technology & Science",
"Birla Institute of Technology, Mesra",
"Birsa Agricultural University",
"Bundelkhand University",
"Burdwan University",
"Calcutta University",
"Calicut University",
"Calrox Teacher's University",
"Central Agricultural University",
"Central Institute of Fisheries Education",
"Central Institute of Higher Tibetan Studies",
"Central University of Bihar",
"Central University of Gujarat",
"Central University of Haryana",
"Central University of Himachal Pradesh",
"Central University of Jammu",
"Central University of Jharkhand",
"Central University of Karnataka",
"Central University of Kashmir",
"Central University of Kerala",
"Central University of Orissa",
"Central University of Punjab",
"Central University of Rajasthan",
"Central University of Tamil Nadu",
"Centre for Environmental Planning and Technology University",
"Chanakya National Law University",
"Chandra Shekhar Azad University of Agriculture & Technology",
"Charotar University of Science & Technology",
"Chaudhary Devi Lal University",
"Chennai Mathematical Institute",
"Chettinad Academy of Research & Education (CARE)",
"Chhatrapati Shahuji Maharaj Medical University",
"Chhattisgarh Swami Vivekanand Technical University",
"Chitkara University",
"Choudhary Charan Singh Haryana Agricultural University",
"Choudhary Charan Singh University",
"Christ University",
"Cochin University of Science and Technology",
"D.Y. Patil Educational Society",
"Dakshina Bharat Hindi Prachar Sabha",
"Damodaram Sanjivayya National Law University",
"Datta Meghe Institute of Medical Sciences",
"Davangere University",
"Dayalbagh Educational Institute",
"Deccan College Postgraduate & Research Institute",
"Deen Bandhu Chhotu Ram University of Science & Technology",
"Deen Dayal Upadhyay Gorakhpur University",
"Delhi Technological University",
"Dev Sanskriti Vishwavidyalaya",
"Devi Ahilya Vishwavidyalaya",
"Dharmsinh Desai University",
"Dhirubhai Ambani Institute of Information & Communication Technology",
"Dibrugarh University",
"Doon University",
"Dr B R Ambedkar National Institute of Technology, Jalandhar",
"Dr Ram Manohar Lohia Awadh University",
"Dr. B.R. Ambedkar Open University",
"Dr. B.R. Ambedkar University",
"Dr. B.R. Ambedkar University",
"Dr. Babasaheb Ambedkar Marathwada University",
"Dr. Babasaheb Ambedkar Open University",
"Dr. Babasaheb Ambedkar Technological University",
"Dr. Balasaheb Sawant Konkan Krishi Vidyapeeth",
"Dr. C.V. Raman University",
"Dr. D.Y. Patil Vidyapeeth",
"Dr. Harisingh Gour Vishwavidyalaya",
"Dr. NTR University of Health Sciences",
"Dr. Panjabrao Deshmukh Krishi Vidyapeeth",
"Dr. Ram Manohar Lohiya National Law University",
"Dr. Shakuntala Misra Rehabilitation University",
"Dr. Y.S.Parmar University of Horticulture & Forestry",
"Dravidian University",
"Eastern Institute for Integrated Learning in Management University",
"English and Foreign Languages University",
"Eternal University",
"Fakir Mohan University",
"Forest Research Institute",
"G.B. Pant University of Agriculture and Technology",
"Gandhi Institute of Technology and Management (GITAM)",
"Gandhigram Rural Institute",
"Ganpat University",
"Gauhati University",
"Gaur Banga University",
"Gautam Buddha Technical University",
"Gautam Buddha University",
"Goa University",
"Gokhale Institute of Politics & Economics",
"Graphic Era University",
"Gujarat Agricultural University",
"Gujarat Ayurveda University",
"Gujarat National Law University",
"Gujarat Technological University",
"Gujarat University",
"Gujarat Vidyapith",
"Gulbarga University",
"Guru Angad Dev Veterinary & Animal Sciences University",
"Guru Ghasidas Vishwavidyalaya",
"Guru Gobind Singh Indraprastha Vishwavidyalaya",
"Guru Jambeshwar University of Science And Technology",
"Guru Nanak Dev University",
"Gurukul Kangri Vishwavidyalaya",
"Hemchandracharya North Gujarat University",
"Hemwati Nandan Bahuguna Garhwal University",
"Hidayatullah National Law University",
"HIHT University",
"Himachal Pradesh University",
"Himachal Pradhesh Agriculture University",
"Himgiri Zee University",
"Hindustan Institute of Technology and Science (HITS)",
"Homi Bhabha National Institute",
"I.I.S. University",
"ICFAI Foundation for Higher Education",
"IIM Ahmedabad : Indian Institute of Management, Ahmedabad",
"IIM Bangalore : Indian Institute of Management, Bangalore",
"IIM Calcutta : Indian Institute of Management, Calcutta",
"IIM Indore : Indian Institute of Management, Indore",
"IIM Kashipur : Indian Institute of Management, Kashipur",
"IIM Kozhikode : Indian Institute of Management, Kozhikode",
"IIM Lucknow : Indian Institute of Management, Lucknow",
"IIM Raipur : Indian Institute of Management, Raipur",
"IIM Ranchi : Indian Institute of Management, Ranchi",
"IIM Rohtak : Indian Institute of Management, Rohtak",
"IIM Shillong : Indian Institute of Management, Shillong",
"IIM Tiruchirappalli : Indian Institute of Management, Tiruchirappalli",
"IIPS Mumbai : International Institute for Population Sciences",
"IISc Bangalore : Indian Institute of Science",
"IISER Bhopal : Indian Institutes of Science Education and Research, Bhopal",
"IISER Kolkata : Indian Institutes of Science Education and Research, Kolkata",
"IISER Mohali : Indian Institutes of Science Education and Research, Mohali",
"IISER Pune : Indian Institutes of Science Education and Research, Pune",
"IISER Thiruvananthpuram : Indian Institutes of Science Education and Research, Thiruvananthpuram",
"IIST : Indian Institute of Space Science and Technology",
"IIT Bhubaneswar : Indian Institute of Technology, Bhubaneswar",
"IIT Bombay : Indian Institute of Technology, Mumbai",
"IIT Delhi : Indian Institute of Technology, Delhi",
"IIT Gandhinagar : Indian Institute of Technology, Gandhinagar",
"IIT Guwahati : Indian Institute of Technology, Guwahati",
"IIT Hyderabad : Indian Institute of Technology, Hyderabad",
"IIT Indore : Indian Institute of Technology, Indore",
"IIT Kanpur : Indian Institute of Technology, Kanpur",
"IIT Kharagpur : Indian Institute of Technology, Kharagpur",
"IIT Madras : Indian Institute of Technology, Madras",
"IIT Mandi : Indian Institute of Technology, Mandi",
"IIT Patna : Indian Institute of Technology, Patna",
"IIT Rajasthan : Indian Institute of Technology Rajasthan",
"IIT Roorkee : Indian Institute of Technology, Roorkee",
"IIT Ropar : Indian Institute of Technology, Ropar",
"Indian Agricultural Research Institute",
"Indian Institute of Engineering Science and Technology (IIEST)",
"Indian Institute of Engineering, Rajasthan",
"Indian Institute of Foreign Trade(IIFT)",
"Indian Institute of Information Technology and Management",
"Indian Institute of Information Technology, Allahabad",
"Indian Institute of Information Technology, Bhubaneswar",
"Indian Law Institute",
"Indian Maritime University",
"Indian Statistical Institute, Bangalore",
"Indian Statistical Institute, Chennai",
"Indian Statistical Institute, Delhi",
"Indian Statistical Institute, Hyderabad",
"Indian Statistical Institute, Kolkata",
"Indian Statistical Institute, Mumbai",
"Indian Veterinary Research Institute",
"Indira Gandhi Agricultural University",
"Indira Gandhi Institute of Development Research",
"Indira Gandhi National Open University",
"Indira Kala Sangeet Vishwavidyalaya",
"Indraprastha Institute of Information Technology, Delhi",
"Indus International University",
"Institute of Advanced Studies in Education",
"Institute of Armament Technology",
"Institute of Chartered Financial Analysts of India (ICFAI)",
"Institute of Chemical Technology",
"Institute of Liver and Biliary Sciences(ILBS)",
"Integral University",
"International Institute of Information Technology, Bangalore",
"International Institute of Information Technology, Hyderabad",
"Islamic University of Science & Technology",
"ISM : Indian School of Mines",
"IT Varanasi: Institute of Technology Banaras Hindu University, Varanasi",
"ITM University",
"Jadavpur University",
"Jagadguru Ramanandacharya Sanskrit University",
"Jagadguru Rambhadracharya Handicapped University",
"Jagadguru Sri Shivarathreeswara University",
"Jagannath University",
"Jai Narain Vyas University",
"Jai Prakash University",
"Jain University",
"Jain Vishva Bharati Institute",
"Jaipur National University",
"Jamia Hamdard",
"Jamia Millia Islamia",
"Jammu University",
"Janardan Rai Nagar Rajasthan Vidyapeeth",
"Jawahar Lal Nehru University",
"Jawaharlal Institute of Postgraduate Medical Education & Research",
"Jawaharlal Nehru Architecture and Fine Arts University",
"Jawaharlal Nehru Centre for Advanced Scientific Research",
"Jawaharlal Nehru Krishi Vishwavidyalaya",
"Jawaharlal Nehru Technological University",
"Jawaharlal Nehru Technological University",
"Jawaharlal Nehru Technological University",
"Jaypee Institute of Information Technology",
"Jaypee University of Engineering & Technology",
"Jaypee University of Information Technology",
"Jiwaji University",
"Jodhpur National University",
"Jyoti Vidyapeeth Women's University",
"K.L.E. Academy of Higher Education and Research",
"Kadi Sarva Vishwavidyalaya",
"Kakatiya University",
"Kalasalingam Academy of Research and Higher Education",
"Kalinga Insitute of Industrial Technology",
"Kalyani University",
"Kameshwar Singh Darbhanga Sanskrit University",
"Kannada University",
"Kannur University",
"Karnataka University",
"Karnataka State Law University",
"Karnataka State Open University",
"Karnataka State Women University",
"Karnataka Veterinary Animal and Fisheries Science University",
"Karpagam Academy of Higher Education",
"Karunya Institute of Technology and Sciences",
"Kashmir University",
"Kavi Kulguru Kalidas Sanskrit Vishwavidyalaya",
"Kerala Agricultural University",
"Kerala Kalamandalam",
"Kerala University",
"Kolhan University",
"Koneru Lakshmaiah Education Foundation",
"Krantiguru Shyamji Krishna Verma Kachchh University",
"Krishna Institute of Medical Sciences",
"Krishna Kanta Handique State Open University",
"Krishna University",
"Kumaun University",
"Kurukshetra University",
"Kushabhau Thakre Patrakarita Avam Jansanchar Vishwavidyala",
"Kuvempu University",
"Lakshmibai National Institute of Physical Education",
"Lalit Narayan Mithila University",
"Lingaya's University",
"LNM Institute of Information Technology",
"Lovely Professional University",
"Lucknow University",
"M.G. Gramodaya Vishwavidyalaya",
"M.G.R. Educational and Research Institute",
"M.J.P.Rohilkhand University",
"M.P.Bhoj (open) University",
"Madhya Pradesh Pashu Chikitsa Vigyan Vishwavidyalaya",
"Madras University",
"Madurai Kamraj University",
"Magadh University",
"Mahamaya Technical University",
"Maharaja Ganga Singh University",
"Maharaja Krishnakumarsinhji Bhavnagar University",
"Maharaja Sayajirao University of Baroda",
"Maharana Pratap University of Agriculture and Technology",
"Maharashtra Animal & Fishery Sciences University",
"Maharashtra State Board of Secondary and Higher Secondary Education",
"Maharashtra State Board of Technical Education",
"Maharashtra State Board of Vocational Education",
"Maharashtra University of Health Sciences",
"Maharishi Dayanand Saraswati University",
"Maharishi Dayanand University",
"Maharishi Mahesh Yogi Vedic Vishwavidyalaya",
"Maharishi Markandeshwar University",
"Maharishi Panini Sanskrit Vishwavidyalaya",
"Maharishi University of Management and Technology",
"Mahatma Gandhi Antarrashtriya Hindi Vishwavidyalaya",
"Mahatma Gandhi Kashi Vidyapeeth",
"Mahatma Gandhi University",
"Mahatma Gandhi Univesity",
"Mahatma Jyoti Rao Phoole University",
"Mahatma Phule Krishi Vidyapeeth",
"Makhanlal Chaturvedi Rashtriya Patrakarita National University of Journalism",
"Malaviya National Institute of Technology, Jaipur",
"Manav Bharti University",
"Manav Rachna International University",
"Mangalayatan University",
"Mangalore University",
"Manipal Academy of Higher Education",
"Manipur University",
"Manonmaniam Sundarnar University",
"Marathwada Agricultural University",
"Martin Luther Christian University",
"MATS University",
"Maulana Azad National Institute of Technology, Bhopal",
"Maulana Azad National Urdu University",
"Maulana Mazharul Haque Arabic & Persian University",
"Meenakshi Academy of Higher Education and Research",
"Meghalaya University of Science & Technology",
"Mewar University",
"MGM Institute of Health Sciences",
"Mizoram University",
"Mody Institute of Technology & Science?",
"Mohammad Ali Jauhar University",
"Mohan Lal Sukhadia University",
"Mother Teresa Women's University",
"Motilal Nehru National Institute of Technology, Allahabad",
"Mumbai University",
"Mysore University",
"Nagaland University",
"Nalanda Open University",
"Narendra Deo University of Agriculture & Technology",
"Narsee Monjee Institute of Management Studies",
"National Academy of Legal Studies & Research University",
"National Brain Research Centre",
"National Dairy Research Institute",
"National Institute of Mental Health & Neuro Sciences",
"National Institute of Pharmaceutical Education & Research, Ahmedabad (NIPER)",
"National Institute of Pharmaceutical Education & Research, Guwahati (NIPER)",
"National Institute of Pharmaceutical Education & Research, Hajipur (NIPER)",
"National Institute of Pharmaceutical Education & Research, Hyderabad (NIPER)",
"National Institute of Pharmaceutical Education & Research, Kolkata (NIPER)",
"National Institute of Pharmaceutical Education & Research, Rae Barelli (NIPER)",
"National Institute of Pharmaceutical Education & Research, S.A.S. Nagar (NIPER)",
"National Institute of Technology, Agartala",
"National Institute of Technology, Calicut",
"National Institute of Technology, Durgapur",
"National Institute of Technology, Hamirpur",
"National Institute of Technology, Jamshedpur",
"National Institute of Technology, Kurukshetra",
"National Institute of Technology, Patna",
"National Institute of Technology, Raipur",
"National Institute of Technology, Rourkela",
"National Institute of Technology, Silchar",
"National Institute of Technology, Srinagar",
"National Institute of Technology, Surathkal",
"National Institute of Technology, Tiruchirapalli",
"National Institute of Technology, Warangal",
"National Institutes of Science Education and Research, Bhubaneswar (NISER)",
"National Law Institute University",
"National law School of India University",
"National Law University",
"National Law University",
"National Law University, Delhi",
"National Museum Institute of History of Art, Conservation and Musicology, National Museum",
"National School of Drama",
"National University of Advanced Legal Studies",
"National University of Educational Planning & Administration",
"Nava Nalanda Mahavihara",
"Nehru Gram Bharati",
"Netaji Subhash Open University",
"Nilamber-Pitamber University",
"NIMS University",
"Nirma University of Science & Technology",
"NITTE University",
"Noorul Islam Center for Higher Education",
"North Bengal University",
"North Eastern Hill University",
"North Eastern Regional Institute of Science & Technology",
"North Maharashtra University",
"North Orissa University",
"O.P. Jindal Global University",
"Orissa University of Agriculture & Technology",
"Osmania University",
"Padmashree Dr. D.Y. Patl Vidyapeeth",
"Palamuru University",
"Pandit Deendayal Petroleum University",
"Pandit Dwarka Prasad Mishra Indian Institute of Information Technology, Design & Manufacturing",
"Pandit Ravishankar Shukla University",
"Pandit Sundarlal Sharma (Open) University",
"Patna University",
"Periyar Maniammai Institute of Science & Technology (PMIST)",
"Periyar University",
"Pondicherry University",
"Ponnaiyah Ramajayam Institute of Science & Technology (PRIST)",
"Post Graduate Institute of Medical Education and Research",
"Potti Sreeramulu Telugu University",
"Pravara Institute of Medical Sciences",
"Presidency University",
"Pt. Bhagwat Dayal Sharma University of Health Sciences",
"Punjab Agricultural University",
"Punjab Engineering College",
"Punjab Technical University",
"Punjab University",
"Punjabi University",
"Rabindra Bharati University",
"Rajasthan Agricultural University",
"Rajasthan Ayurveda University",
"Rajasthan Technical University",
"Rajasthan University",
"Rajasthan University of Health Sciences",
"Rajendra Agricultural University",
"Rajiv Gandhi Institute of Petroleum Technology",
"Rajiv Gandhi National Institute of Youth Development",
"Rajiv Gandhi Prodoyogiki Vishwavidyalaya",
"Rajiv Gandhi University",
"Rajiv Gandhi University of Health Sciences",
"Ramakrishna Mission Vivekananda Educational and Research Institute",
"Ranchi University",
"Rani Durgavati Vishwavidyalaya",
"Rashtriya Sanskrit Sansthana",
"Rashtriya Sanskrit Vidyapeeth",
"Ravenshaw University",
"Rayalaseema University",
"S V National Institute of Technology, Surat",
"S.R.M Institute of Science and Technology",
"Sam Higginbottom Institute of Agriculture, Technology & Sciences",
"Sambalpur University",
"Sampurnanand Sanskrit Vishwavidyalaya",
"Sant Gadge Baba Amravati University",
"Sant Longowal Institute of Engineering and Technology (SLIET)",
"Santosh University",
"Sardar Patel University",
"Sardar Vallabh Bhai Patel University of Agriculture & Technology",
"Sarguja University",
"Satavahana University",
"Sathyabama Institute of Science and Technology",
"Saurashtra University",
"Saveetha Institute of Medical and Technical Sciences",
"School of Planning & Architecture",
"State council for technical Education and vocational training",
"Shanmugha Arts, Science, Technology & Research Academy (SASTRA)",
"Sharda University",
"Sher-e-Kashmir University of Agricultural Science & Technology of Jammu",
"Sher-e-Kashmir University of Agricultural Science & Technology of Kashmir",
"Shiksha 'O' Anusandhan",
"Shivaji University",
"Shobhit Institute of Engineering & Technology",
"Shoolini University",
"Shree Sankaracharya University of Sanskrit",
"Shree Somnath Sanskrit University",
"Shreemati Nathibai Damodar Thackersey Women's University (SNDT)",
"Shri Jagannath Sanskrit Vishwavidyalaya",
"Shri Jagdish Prasad Jhabarmal Tibrewala University",
"Shri Lal Bahadur Shastri Rashtriya Sanskrit Vidyapith",
"Shri Mata Vaishno Devi University",
"Shridhar University",
"Sidho-Kanho-Birsha University",
"Sido Kanhu University",
"Sikkim Manipal University of Health Medical & Technological Science",
"Sikkim University",
"Singhania University",
"Solapur University",
"South Gujarat University",
"Sree Chitra Thirunal Institute of Medical Sciences and Technology",
"Sri Balaji Vidyapeeth",
"Sri Chandrasekharendra Saraswathi Vishwa Mahavidyalaya",
"Sri Devraj Urs Academy of Higher Education and Research",
"Sri Krishnadevaraya University",
"Sri Padmapat Singhania University",
"Sri Padmavati Mahila Vishwavidyalayam",
"Sri Ramachandra Medical College and Research Institute",
"Sri Sathya Sai Institute of Higher Learning",
"Sri Siddhartha Academy of Higher Education",
"Sri Venkateswara University",
"Sri Venkateswara Vedic University",
"Sri Venkateswara Veterinary University",
"St. Peter's Institute of Higher Education and Research",
"Sumandeep Vidyapeeth",
"Suresh Gyan Vihar University",
"Swami Ramanand Teerth Marathwada University",
"Swami Vivekanand Subharti University",
"Swami Vivekananda Yoga Anusandhana Samsthana",
"SYMBIOSIS International University",
"Tamil Nadu Open University",
"Tamil Nadu Teacher Education University",
"Tamil University",
"Tamilnadu Agricultural University",
"Tamilnadu Dr. Ambedkar Law University",
"Tamilnadu Dr. M.G.R. Medical University",
"Tamilnadu Physical Education and Sports University",
"Tamilnadu Veterinary & Animal Sciences University",
"Tata Institute of Fundamental Research",
"Tata Institute of Social Sciences",
"Techno Global University",
"Teerthanker Mahaveer University",
"Telangana University",
"TERI School of Advanced Studies",
"Tezpur University",
"Thapar Institute of Engineering & Technology",
"The Aeronautical Society of India (AeSI)",
"The Bengal Engineering & Science University",
"The Global Open University",
"The Indira Gandhi National Tribal University",
"The Institute of Chartered Accountants of India (ICAI)",
"The Institute of Chartered Financial Analysts of India University, Jharkhand(ICFAI)",
"The Institute of Chartered Financial Analysts of India University, Meghalaya(ICFAI)",
"The Institute of Chartered Financial Analysts of India University, Mizoram(ICFAI)",
"The Institute of Chartered Financial Analysts of India University, Nagaland(ICFAI)",
"The Institute of Chartered Financial Analysts of India University, Sikkim(ICFAI)",
"The Institute of Chartered Financial Analysts of India University, Tripura(ICFAI)",
"The Rajiv Gandhi National University of Law",
"The Rashtrasant Tukadoji Maharaj Nagpur University",
"The University of Pune",
"The West Bengal National University of Juridical Science",
"The West Bengal University of Health Sciences",
"Thiruvalluvar University",
"Tilak Maharashtra Vidyapeeth",
"Tilka Manjhi Bhagalpur University",
"Tripura University",
"Tumkur University",
"U.P. King George's University of Dental Science",
"U.P. Rajarshi Tandon Open University",
"University of Agricultural Sciences",
"University of Agricultural Sciences",
"University of Allahabad",
"University of Delhi",
"University of Hyderabad",
"University of Kota",
"University of Patanjali",
"University of Petroleum and Energy Studies",
"Utkal University",
"Utkal University of Culture",
"Uttar Banga Krishi Vishwavidyalaya",
"Uttaranchal Sanskrit University",
"Uttrakhand Technical University",
"Vardhman Mahaveer Open University",
"Veer Bahadur Singh Purvanchal University",
"Veer Kunwar Singh University",
"Veer Surendra Sai University of Technology",
"Vel Tech Rangrajan Dr. Sagunthala R&D Institute of Science & Technology",
"Vel's Institute of Science, Technology & Advanced Studies (VISTAS)",
"Vellore Institute of Technology",
"Vidya Sagar University",
"Vignan's Foundation of Science, Technology & Research",
"Vikram Simhapuri University",
"Vikram University",
"Vinayaka Mission's University",
"Vinayaka Missions Sikkim University",
"Vinoba Bhave University",
"Visva Bharati University",
"Visvesvaraya National Institute of Technology, Nagpur",
"Visvesvaraya Technological University",
"West Bengal State University",
"West Bengal University of Animal and Fishery Sciences",
"West Bengal University of Technology",
"West Bengal University of Technology",
"Yashwant Rao Chavan Maharashtra Open University",
"Yenepoya University",
"YMCA University of Science & Technology",
"Yogi Vemana University"] 
  


export default university;